package hanghae.four.taxiservice.unit.infrastructures.client

import hanghae.four.taxiservice.domain.client.Client
import hanghae.four.taxiservice.domain.client.ClientReader
import java.util.concurrent.atomic.AtomicLong

class FakeClientRepository : ClientReader {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    private val clients: ArrayList<Client> = ArrayList()

    fun save(client: Client): Client {
        if (client.id == null) {
            val saveClient = Client(
                id = autoGeneratedId.incrementAndGet()
            )

            clients.add(saveClient)
            return saveClient
        }

        clients.removeIf { c -> c.id == client.id }
        clients.add(client)
        return client
    }

    override fun getClient(clientId: Long): Client {
        return clients.filter { c -> c.id == clientId }.first()
    }
}
