package hanghae.four.taxiservice.unit.infrastructures.taxi

import hanghae.four.taxiservice.domain.taxi.Taxi
import hanghae.four.taxiservice.domain.taxi.TaxiStore
import java.util.concurrent.atomic.AtomicLong

class FakeTaxiStore : TaxiStore {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    private val taxis: ArrayList<Taxi> = ArrayList()

    override fun store(taxi: Taxi): Taxi {
        if (taxi.id == null) {
            val saveTaxi = Taxi(
                id = autoGeneratedId.incrementAndGet(),
                driverId = taxi.driverId,
                type = taxi.type,
                number = taxi.number,
                status = taxi.status
            )

            taxis.add(saveTaxi)
            return saveTaxi
        }

        taxis.removeIf { t -> t.id == taxi.id }
        taxis.add(taxi)
        return taxi
    }
}
