package hanghae.four.taxiservice.unit.infrastructures.pay

import hanghae.four.taxiservice.domain.pay.Payment
import hanghae.four.taxiservice.domain.pay.PaymentStore
import java.util.concurrent.atomic.AtomicLong

class FakePaymentRepository : PaymentStore {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    private val paymentHistories: ArrayList<Payment> = ArrayList()

    override fun store(paymentHistory: Payment): Payment {
        if (paymentHistory.id == null) {
            val savePaymentHistory = Payment(
                id = autoGeneratedId.incrementAndGet(),
                clientId = paymentHistory.clientId,
                callId = paymentHistory.callId,
                type = paymentHistory.type,
                amount = paymentHistory.amount
            )

            paymentHistories.add(savePaymentHistory)
            return savePaymentHistory
        }

        paymentHistories.removeIf { p -> p.id == paymentHistory.id }
        paymentHistories.add(paymentHistory)
        return paymentHistory
    }
}
